# Site settings
title: Andrew Mullins - Blog
email: mullinsajl+blog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal webpage and blog of Andrew Mullins. Data science and statistics
  using R, Python and Julia.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: andrewjmullins 
github_username: andrewjlm 

# Build settings
markdown: kramdown
highlighter: pygments

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Andrew"
